name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}    
    strategy:      
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        build_type: [Release]
        c_compiler: [clang]
        python-version: ["3.12"]
        include:
          - os: ubuntu-latest
            apt: 10
          - os: macos-14
            brew: 20
    steps:
      - name: mamba-setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: moose
          create-args: >-
            python=${{ matrix.python-version }}
            hdf5
            graphviz
            pytables
            numpy
            matplotlib
            vpython
            lxml
            doxygen
            setuptools
            wheel
          cache-environment: true
          cache-downloads: true
          post-cleanup: all
          generate-run-shell: false
      - name: Activate micromamba (non-windows)
        if: runner.os != 'Windows'
        run: |
          eval "$(micromamba shell hook --shell bash)"
          micromamba list
          micromamba info
          which micromamba
          micromamba activate moose
      - name: Activate micromamba (windows)
        if: runner.os == 'Windows'
        run: |
          micromamba shell hook -s powershell | Out-String | Invoke-Expression
          micromamba list
          micromamba info
          which micromamba
          micromamba activate moose
      - name: Display Python version (windows)
        run: python -c "import sys; print(sys.version)"
      - name: Display C++
        run: clang --version
