name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}    
    strategy:      
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        build_type: [Release]
        c_compiler: [clang]
        python-version: ["3.12"]
        include:
          - os: ubuntu-latest
            apt: 10
          - os: macos-14
            brew: 20
    steps:
      - name: mamba-setup
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: moose
          cache-environment: true
          cache-downloads: true
          create-args: >-
            python=${{ matrix.python-version }}
            hdf5
            graphviz
            pytables
            numpy
            matplotlib
            vpython
            lxml
            doxygen
            setuptools
            wheel
      - name: Display Python version
        run: |          
          python -c "import sys; print(sys.version)"
      - name: Display C++
        run: |
          clang
